server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: Root@1234
    url: jdbc:mysql://120.78.145.12:3306/lottery_test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.szxfd.springboot.web.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug