server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: Root@1234
    url: jdbc:mysql://120.78.145.12:3306/lottery_dev?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      #springboot单张图片的上传最大值
      max-file-size: 10MB
      #springboot单次请求（可能多张图片）的上传最大值
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.szxfd.springboot.web.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug