server:
  port: 8888

spring:
  profiles:
    active: prod
  datasource:
    username: root
    password: Root@1234
    url: jdbc:mysql://120.78.145.12:3306/lottery
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.szxfd.springboot.web.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug